version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 590183705133.dkr.ecr.ap-south-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker images...

      - docker build -t aswarda .
	  - docker tag aswarda:latest 590183705133.dkr.ecr.ap-south-1.amazonaws.com/aswarda:latest
	  

  post_build:
    commands:
      - echo Build completed on date
      - docker push 590183705133.dkr.ecr.ap-south-1.amazonaws.com/aswarda:latest
